# Generated by Django 5.0.6 on 2024-06-06 06:18

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.server_banner_upload_path
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.server_icon_upload_path
            ),
        ),
    ]
